import { test, expect } from '@playwright/test';
import { fileURLToPath } from 'node:url';
const screenshot = (name: string) => fileURLToPath(new URL(`../../docs/screenshots/${name}`, import.meta.url));
const evidence = (count: number) => `system: recovery-service\nperiod: 2026-Q3\nreviewed_users: ${count}\nexceptions: 0`;

test('external invitation, revision and independent reapproval', async ({ page, browser }) => {
  test.setTimeout(90000);
  await page.goto('/');
  await page.getByRole('button', {name:/REQ-BACKUP Recovery drill/}).click();
  await page.getByRole('button', {name:'Create invitation'}).click();
  const link = await page.getByLabel('Invitation link').inputValue();
  const context = await browser.newContext();
  const external = await context.newPage();
  await external.goto(link);
  expect(new URL(external.url()).hash).toBe('#invitation');
  await external.getByLabel('Your name').fill('Taylor · External operations');
  await external.getByRole('button', {name:'Accept invitation'}).click();
  await expect(external.getByLabel('Demo persona')).toHaveCount(0);
  await expect(external.getByRole('button', {name:'Approve record'})).toHaveCount(0);
  await expect(external.getByRole('button',{name:/REQ-ACCESS/})).toHaveCount(0);
  await external.getByLabel('Evidence content').fill(evidence(84));
  await external.getByRole('button',{name:'Submit sample evidence'}).click();
  await expect(external.getByText('Evidence accepted. A durable processing job was queued.')).toBeVisible();
  await page.getByRole('button',{name:'Process queued documents'}).click();
  await page.getByLabel('Reviewer feedback').fill('Please correct the reviewed user count.');
  await page.getByRole('button',{name:'Request changes'}).click();
  await external.getByRole('button',{name:'Refresh workspace'}).click();
  await external.getByLabel('Document to replace').selectOption({index:1});
  await external.getByLabel('Evidence content').fill(evidence(91));
  await external.getByRole('button',{name:'Submit sample evidence'}).click();
  await expect(external.getByText('Evidence accepted. A durable processing job was queued.')).toBeVisible();
  await page.getByRole('button',{name:'Process queued documents'}).click();
  await expect(page.getByText('91',{exact:true}).first()).toBeVisible();
  await expect(page.getByText('Superseded',{exact:true})).toHaveCount(1);
  await page.screenshot({path:screenshot('collaboration-revisions.png'),fullPage:true, mask:[page.getByLabel('Invitation link')]});
  await page.getByRole('button',{name:'Approve record'}).click();
  await expect(page.getByTestId('request-status')).toHaveText('APPROVED');
  await page.getByLabel('Reopen reason').fill('Updated evidence received after approval.');
  await page.getByRole('button',{name:'Reopen for review'}).click();
  await expect(page.getByRole('button',{name:'Approve record'})).toBeDisabled();
  await external.getByRole('button',{name:'Refresh workspace'}).click();
  await external.getByLabel('Document to replace').selectOption({index:1});
  await external.getByLabel('Evidence content').fill(evidence(92));
  await external.getByRole('button',{name:'Submit sample evidence'}).click();
  await expect(external.getByText('Evidence accepted. A durable processing job was queued.')).toBeVisible();
  await page.getByRole('button',{name:'Process queued documents'}).click();
  await page.getByRole('button',{name:'Approve record'}).click();
  await expect(page.getByTestId('request-status')).toHaveText('APPROVED');
  await expect(page.getByText('review.approve',{exact:true})).toHaveCount(2);
  await page.screenshot({path:screenshot('collaboration-reapproved.png'),fullPage:true, mask:[page.getByLabel('Invitation link')]});
  await external.getByRole('button',{name:'Refresh workspace'}).click();
  await external.setViewportSize({width:390,height:844});
  expect(await external.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await external.screenshot({path:screenshot('collaboration-external-mobile.png'),fullPage:true});
  await page.getByRole('button',{name:'Revoke invitation'}).first().click();
  await external.getByRole('button',{name:'Refresh workspace'}).click();
  await expect(external.getByText('External session expired or revoked')).toBeVisible();
  await expect(external.getByRole('heading', {name:'Access unavailable'})).toBeVisible({timeout:3000});
  await expect(external.getByRole('heading', {name:'Document versions'})).toHaveCount(0);
  await context.close();
});
